"""empty message

Revision ID: 341520a1c5a6
Revises: 1781e3504f67
Create Date: 2022-05-08 18:48:13.283252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '341520a1c5a6'
down_revision = '1781e3504f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('icon', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'icon')
    # ### end Alembic commands ###
